---
# Repositories
drupal:
  download_location: "/tmp"
  location: "/var/www/html/drupal"
  package_folder: drupal-8.6.7
  package_url: "https://ftp-origin.drupal.org/files/projects"
  package_tar: "drupal-8.6.7.tar.gz"

packages:
  lamp:
    - httpd24
    - php72 
    - php72-cli
    - php72-mysqlnd
    - php72-mbstring
    - php72-gd
    - php72-pdo
    - php72-xml
    - php72-opcache

repo:
  epel: "https://mirror.vcu.edu/pub/gnu_linux/epel/7/x86_64/"
  webtatic: "https://mirror.webtatic.com/yum/el7/webtatic-release.rpm"
