- name: "Add EPEL repo"
  yum_repository:
    name: epel 
    description: "EPEL Repo"
    baseurl: "{{ repo.epel }}"
    gpgcheck: no
    enabled: yes

- name: "Update YUM packages"
  yum:
    name: '*'
    state: latest

- name: Install LAMP packages
  yum:
    name: "{{ packages.lamp }}"
    state: present

- name: Start HTTPD
  systemd:
    name: httpd
    state: started

