- name: "Add EPEL repo"
  yum_repository:
    name: epel 
    description: "EPEL Repo"
    baseurl: "{{ repo.epel }}"
    gpgcheck: no
    enabled: yes

- name: "Add RHEL Optional Repo"
  command: "yum-config-manager --enable rhui-REGION-rhel-server-extras rhui-REGION-rhel-server-optional"

- name: "Update YUM packages"
  yum:
    name: '*'
    state: latest

- name: Install LAMP packages
  yum:
    name: "{{ packages.lamp }}"
    state: present

- name: Start HTTPD
  systemd:
    name: httpd
    state: started

- name: Start firewalld
  systemd:
    name: firewalld
    state: started
    enabled: true

- name: Enable Firewall for httpd
  firewalld:
    service: http
    permanent: yes
    state: enabled

